deployment:
  imageURL: 439481669447.dkr.ecr.us-west-1.amazonaws.com/catalogue
  imageVersion: 1.0.0
hpa:
  maxReplicas: 10
  utilisation: 75
configMap:
  MONGO_URL: mongodb://mongodb:27017/catalogue
